steps:
  # see https://www.npmjs.com/package/editorconfig-checker
  - id: go_test
    name: "gcr.io/cloud-builders/go"
    args: ["build","."]
    env: ["GOPATH=."]
  - id: go_docker
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gohello-image', '.' ]
  images:
  - 'gcr.io/$PROJECT_ID/gohello-image'    
  